name: synctone
description: "Interactive music APP using Spotify API"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.3 <3.7.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  supabase_flutter: ^2.8.3
  flutter_dotenv: ^5.0.2
  animated_notch_bottom_bar: ^1.0.0
  cupertino_icons: ^1.0.8
  flutter_localizations:
    sdk: flutter
  intl: any
  qr_flutter: ^4.1.0
  qr_code_scanner: ^0.5.2
  image_picker: ^1.0.4
  google_maps_flutter: ^2.6.0
  google_maps_flutter_web: ^0.5.4+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo_google.jpg
    - assets/logo_synctone.png
  uses-material-design: true
  generate: true
